### ISSUE TITLE
Make compatible with P5

### ISSUE THREAD

**Issue by 3dogMcNeill** [datakurre/collective.pfg.dexterity#13]
Have a use case for this in P5 site. Can confirm it doesn't work with Plone 5.0. For buildout, need to upgrade pin version for archetypes.referencebrowserwidget. Also had to add this to eggs: "plone.app.contenttypes [atrefs]"

After buildout, addon seems to install with no problems. But in PFG form folder, adding a Content Adapter throws` AttributeError: 'referencebrowser.js'` Also had various other `AttributeError: 'NoneType' object has no attribute 'portal_type'` errors.

**Comment by tkimnguyen** [comment]
please paste here the full error stack!

**Comment by 3dogMcNeill** [comment]
There are multiple errors. It needs to be reworked/rechecked from top to bottom.

**Comment by datakurre** [comment]
I can confirm that I haven't used this on P5 and may not be very soon. I'll move this to collective once I'm back to work (early July) and I can give PYPI rights to anyone who is willing to maintain.

Otherwise the "magic" in this package should still work on P5 in principle.

**Comment by tkimnguyen** [comment]
Thanks Asko. On pypi it seems easiest to grant rights to 'collective'.

**Comment by datakurre** [comment]
I've added collective as owner at PyPI. It seems that I've already forked this repo to collective, so I cannot simply move this repo to collective (because I cannot remove the fork).

**Comment by 3dogMcNeill** [comment]
For anybody who's willing to work on it, there's [some discussion about it on the plone forums](https://community.plone.org/t/anybody-using-collective-pfg-dexterity-with-plone-5/2376).

**Comment by datakurre** [comment]
I'm working on this now, and have fixed the compatibility issues with Plone 5. Once I get my cleanup finished and tests running again, I do a 1.0 release supporting both Plone 4.3 and Plone 5.0.

**Comment by datakurre** [comment]
I'm now working to add support for Plone 5. All main issues solved and just clean up, testing, etc to do.

**Comment by datakurre** [comment]
I've now released 1.0.0rc1, which should support both Plone 4 and Plone 5.

**Comment by 3dogMcNeill** [comment]
Awesome, Asko, thanks!
